package common

const CLIENT_TYPE = "CLIENT_TYPE"

const REDIS_HOST = "REDIS_HOST"
const REDIS_PORT = "REDIS_PORT"
const REDIS_MASTERNAME = "REDIS_MASTERNAME"
const REDIS_USER = "REDIS_USER"
const REDIS_PASSWORD = "REDIS_PASSWORD"
const REDIS_DB_NO = "REDIS_DB_NO"
